### ISSUE TITLE
Concurrent Modification Crash

### ISSUE THREAD

**Issue by jmilthedude** [Xratedjunior/Better-Default-Biomes#35]
In a RAD2 server which has been running for a bit over a month, we suddenly receive this crash on launch. 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) ~[?:1.8.0_312] {}
-- MOD betterdefaultbiomes --
Details:
	Mod File: BetterDefaultBiomes-1.16.4+-Alpha 2.6.1.jar
	Failure message: Better Default Biomes (betterdefaultbiomes) encountered an error during the common_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: Alpha 2.6.0
	Mod Issue URL: https://github.com/Xratedjunior/Better-Default-Biomes/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) ~[?:1.8.0_312] {}
	at java.util.HashMap$EntryIterator.next(HashMap.java:1503) ~[?:1.8.0_312] {}
	at java.util.HashMap$EntryIterator.next(HashMap.java:1501) ~[?:1.8.0_312] {}
	at java.util.HashMap.putMapEntries(HashMap.java:513) ~[?:1.8.0_312] {}
	at java.util.HashMap.<init>(HashMap.java:491) ~[?:1.8.0_312] {}
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
	at xratedjunior.betterdefaultbiomes.init.BDBVanillaCompat.registerStrippable(BDBVanillaCompat.java:81) ~[betterdefaultbiomes:1.16.4+-Alpha 2.6.1] {re:classloading}
	at xratedjunior.betterdefaultbiomes.init.BDBVanillaCompat.setup(BDBVanillaCompat.java:18) ~[betterdefaultbiomes:1.16.4+-Alpha 2.6.1] {re:classloading}
	at xratedjunior.betterdefaultbiomes.BetterDefaultBiomes.commonSetup(BetterDefaultBiomes.java:129) ~[betterdefaultbiomes:1.16.4+-Alpha 2.6.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_312] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_312] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_312] {}

**Comment by Xratedjunior** [comment]
@jmilthedude Did you update any other mods by chance? (Which also add logs)

**Comment by jmilthedude** [comment]
No I haven't updated anything. I haven't been on this server in a couple weeks and just saw it in a crashed state when I opened this issue. Went to start it and it will no longer start without this crash.

**Comment by Xratedjunior** [comment]
Not enough info to fix;
Cleaning up old issues
